// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4X2zCLAVsbAOKgnapJWh8xDiQXfd7fM',
    appId: '1:49140893338:web:2f099d7421dbf8937a0123',
    messagingSenderId: '49140893338',
    projectId: 'ethico-meeting',
    authDomain: 'ethico-meeting.firebaseapp.com',
    storageBucket: 'ethico-meeting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUBgvq7kQvdV91tdQuWlUfMU5mzxNygeQ',
    appId: '1:49140893338:android:72c2505964c8b8c37a0123',
    messagingSenderId: '49140893338',
    projectId: 'ethico-meeting',
    storageBucket: 'ethico-meeting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrXdVWzea_hmufm2GypPz7NYPPOqnrHwI',
    appId: '1:49140893338:ios:f795bbb698951cab7a0123',
    messagingSenderId: '49140893338',
    projectId: 'ethico-meeting',
    storageBucket: 'ethico-meeting.appspot.com',
    iosBundleId: 'com.example.ethicoMeeting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrXdVWzea_hmufm2GypPz7NYPPOqnrHwI',
    appId: '1:49140893338:ios:5154b62b00dd57987a0123',
    messagingSenderId: '49140893338',
    projectId: 'ethico-meeting',
    storageBucket: 'ethico-meeting.appspot.com',
    iosBundleId: 'com.example.ethicoMeeting.RunnerTests',
  );
}
